/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bookmark: typeof import('./src/components/Bookmark.vue')['default']
    Car: typeof import('./src/components/Car.vue')['default']
    Entertainment: typeof import('./src/components/Entertainment.vue')['default']
    Hot: typeof import('./src/components/Hot.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewList: typeof import('./src/components/NewList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sport: typeof import('./src/components/Sport.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
